version: "3.9"
services:
  app:
    build: .
    container_name: banking-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbit-mq
    environment:
        - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
        - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
        - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
        - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
        - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
        - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
        - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
    networks:
      - banking-net

  postgres:
    image: postgres:15
    container_name: banking-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - banking-net

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: banking-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - banking-net

networks:
  banking-net:
    driver: bridge